### PR TITLE
Pass extra data via captureException/captureMessage

### PR DESCRIPTION
**Pull request by eliasmelgaco**
I am adding extraParams support provided in the Sentry documentation https://docs.sentry.io/enriching-error-data/context/?platform=browser#extra-context

@Turbo87

### CODE REVIEW

**Comment by eliasmelgaco** [comment]
@Turbo87

**Comment by Turbo87** [comment]
https://docs.sentry.io/enriching-error-data/context/?platform=browser#extra-context refers to their new SDK, but `ember-cli-sentry` is still using `raven-js` internally. are you sure that the same is possible with `raven-js`?

**Comment by villander** [comment]
yup @Turbo87 extra params is support by `raven-js`, I tested this branch in my app and works very fine.

https://github.com/getsentry/sentry-javascript/blob/a01b4ee7f7ba03167d7424daae2fb2f2206687cb/packages/raven-js/test/raven.test.js#L588-L600

can we merge this?

**Comment by Turbo87** [comment]
the legacy client (`raven-js`) has a `setExtraContext()` method that can be used for the same purpose:

```js
this.raven.callRaven('setExtraContext', {
  whatever: 'you want'
});
```

see https://docs.sentry.io/clients/javascript/usage/#raven-js-additional-context

**Comment by villander** [comment]
thanks @Turbo87

**Comment by eliasmelgaco** [comment]
thanks @Turbo87

**Pull request closed without merging**
